// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChufD-sILawWlrIUhdzmIw5JzFqPZNM9M',
    appId: '1:698214153648:web:c11eb45f1063d94f286a75',
    messagingSenderId: '698214153648',
    projectId: 'ecommerceapp-d90e6',
    authDomain: 'ecommerceapp-d90e6.firebaseapp.com',
    storageBucket: 'ecommerceapp-d90e6.firebasestorage.app',
    measurementId: 'G-FCNTPZHQST',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXpyFyGCs0NopGCQcO8nEGXDMfNEbZK80',
    appId: '1:698214153648:android:a0ec12f2f6f11974286a75',
    messagingSenderId: '698214153648',
    projectId: 'ecommerceapp-d90e6',
    storageBucket: 'ecommerceapp-d90e6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDk1r1o7euHo32n5knoP5HMhwHvQQ2Sdr0',
    appId: '1:698214153648:ios:cbc770afa3f80acb286a75',
    messagingSenderId: '698214153648',
    projectId: 'ecommerceapp-d90e6',
    storageBucket: 'ecommerceapp-d90e6.firebasestorage.app',
    iosBundleId: 'com.example.productx',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDk1r1o7euHo32n5knoP5HMhwHvQQ2Sdr0',
    appId: '1:698214153648:ios:cbc770afa3f80acb286a75',
    messagingSenderId: '698214153648',
    projectId: 'ecommerceapp-d90e6',
    storageBucket: 'ecommerceapp-d90e6.firebasestorage.app',
    iosBundleId: 'com.example.productx',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyChufD-sILawWlrIUhdzmIw5JzFqPZNM9M',
    appId: '1:698214153648:web:2016f5d862b7b928286a75',
    messagingSenderId: '698214153648',
    projectId: 'ecommerceapp-d90e6',
    authDomain: 'ecommerceapp-d90e6.firebaseapp.com',
    storageBucket: 'ecommerceapp-d90e6.firebasestorage.app',
    measurementId: 'G-Z2TCTNB1F1',
  );
}
